apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: payment-delay-chaos
  namespace: techx-tf3
spec:
  action: delay
  mode: all
  duration: 10m
  selector:
    namespaces:
      - techx-tf3
    labelSelectors:
      app.kubernetes.io/name: payment
  delay:
    latency: '5000ms'
    jitter: '200ms'
