apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aiops-engine-role
  namespace: techx-tf3
rules:
- apiGroups: ["apps"]
  resources: ["deployments", "deployments/scale"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aiops-engine-rolebinding
  namespace: techx-tf3
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aiops-engine-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: techx-tf3
