apiVersion: v1
kind: ServiceAccount
metadata:
  name: aiops-engine
  namespace: techx-tf3
  labels:
    app.kubernetes.io/name: aiops-engine
    app.kubernetes.io/managed-by: argocd
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::197826770971:role/tf3-aiops-engine-irsa-role
